name: Latest posts workflow
on:
 schedule:
   - cron: '0 * * * *' 
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest blog posts
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/adiatiayu"
          max_post_count: 5
          template: "- `$date` | [$title]($url)  $newline"
          date_format: yyyy-mm-dd
          tag_post_pre_newline: true
          
